# Welcome to my new website
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Alex's First Website
email: alex.delmaine@yaho.co.uk
description: > # this means to ignore newlines until "baseurl:"
  The following website has been created by Alex Delmaine.
  This is being used for developing and testing purposes so that I can practice
  learning to code.
baseurl: "AlexDelmaine.github.io" # the subpath of your site, e.g. /blog
url: "https://github.com/AlexDelmaine/AlexDelmaine.github.io" # the base hostname & protocol for your site
twitter_username: n/a
github_username:  AlexDelmaine

# Build settings
markdown: kramdown

theme: jekyll-theme-cayman
